project_name: exoscale-grafana-autoscaler
builds:
  - id: exoscale-grafana-autoscaler
    binary: exoscale-grafana-autoscaler
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - exoscale-grafana-autoscaler
    image_templates:
      - "janoszen/exoscale-grafana-autoscaler:latest"
      - "janoszen/exoscale-grafana-autoscaler:{{ .Major }}.{{ .Minor }}"
      - "janoszen/exoscale-grafana-autoscaler:{{ .Tag }}"
      - "docker.pkg.github.com/janoszen/exoscale-grafana-autoscaler/{{.ProjectName}}:latest"
      - "docker.pkg.github.com/janoszen/exoscale-grafana-autoscaler/{{.ProjectName}}:{{ .Major }}.{{ .Minor }}"
      - "docker.pkg.github.com/janoszen/exoscale-grafana-autoscaler/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile.goreleaser
    builds:
      - exoscale-grafana-autoscaler
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
    skip_push: auto
